export enum Fields {
  Name = "name",
  Description = "description",
  IsAvailable = "isAvailable",
  Section = "section",
  SectionId = "sectionId",
  Allergens = "allergens",
  Variants = "variants",
  Variant = "variant",
  ExtraPrice = "extraPrice",
  ExtraIngredients = "extraIngredients",
  RemovableIngredients = "removableIngredients",
  Picture = "picture",
  Background = "background",
  Price = "price",
  DishesList = "dishesList",
  DeliveryMethod = "deliveryMethod",
  TableNumber = "tableNumber",
  HoursOfAvailability = "hoursOfAvailability",
  OpeningHours = "openingHours",
  OpenDays = "openDays",
  Currency = "currency",
  ClientName = "clientName",
  PhoneNumber = "phoneNumber",
  PaymentMethod = "paymentMethod",
}
